---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - /home/igorkulman/docker-services/heimdall:/config
    ports:
      - 8000:80
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - UMASK=000
    volumes:
      - /home/igorkulman/docker-services/radarr/config:/config
      - /media/data:/media
    ports:
      - 7878:7878
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - /home/igorkulman/docker-services/jackett/config:/config
    ports:
      - 9117:9117
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - UMASK=000
    volumes:
      - /home/igorkulman/docker-services/sonarr/config:/config
      - /media/data:/media
    ports:
      - 8989:8989
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - UMASK=000
    volumes:
      - /home/igorkulman/docker-services/transmission/config:/config
      - /media/data/:/media
    ports:
      - 9091:9091
      - 49153:49153
      - 49153:49153/udp
    restart: unless-stopped
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Prague
      - PLEX_CLAIM=XXX
    volumes:
      - /home/igorkulman/docker-services/plex/:/config
      - /media/data:/media
      - /media/data/transcode:/transcode
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    networks:
      pihole:
        ipv4_address: 172.20.0.2
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
    environment:
      - TZ=Europe/Prague
      - PROXY_LOCATION=pihole
      - VIRTUAL_PORT=80
      - PIHOLE_DNS_=172.20.0.3#5053
    volumes:
      - /home/igorkulman/docker-services/pihole/:/etc/pihole/
      - /home/igorkulman/docker-services/dnsmasq.d/:/etc/dnsmasq.d/
    restart: always
  cloudflared:
    image: crazymax/cloudflared:latest
    container_name: cloudflared
    hostname: cloudflared
    networks:
      pihole:
        ipv4_address: 172.20.0.3
    environment:
      - TZ=Europe/Prague
      - TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query
    restart: always
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - /home/igorkulman/docker-services/unifi:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped

networks:
  pihole:
    ipam:
      config:
        - subnet: 172.20.0.0/24
