---
services:
  homer:
    image: homer-custom:latest
    container_name: homer
    volumes:
      - ./homer:/www/assets
    ports:
      - 3000:8080
    user: 1000:1000
    environment:
      - INIT_ASSETS=1
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - UMASK=000
    volumes:
      - ./radarr/config:/config
      - /media/data:/media
    ports:
      - 7878:7878
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Prague
    ports:
      - "8191:8191"
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - UMASK=000
    volumes:
      - ./sonarr/config:/config
      - /media/data:/media
    ports:
      - 8989:8989
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - UMASK=000
    volumes:
      - ./transmission/config:/config
      - /media/data/:/media
    ports:
      - 9091:9091
      - 49153:49153
      - 49153:49153/udp
    restart: unless-stopped
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: always
    ports:
      - "3003:3001"
    volumes:
      - ./uptime-kuma:/app/data
    environment:
      - UPTIME_KUMA_WS_ORIGIN_CHECK=bypass
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Prague
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ./plex/:/config
      - /media/data:/media
      - /media/data/transcode:/transcode
    privileged: true
    devices:
      - /dev/dri:/dev/dri
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_SCHEDULE=0 0 4 * * *
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_NOTIFICATIONS_LEVEL=debug
      - WATCHTOWER_CLEANUP=true
      - TZ=Europe/Prague
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
  unifi-controller:
    image: jacobalberty/unifi:v8
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024
      - MEM_STARTUP=1024
      - UNIFI_UID=1000
      - UNIFI_GID=1000
      - TZ=Europe/Prague
    volumes:
      - ./unifi:/unifi
    network_mode: host
    restart: unless-stopped
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Prague
    volumes:
      - ./prowlarr:/config
    restart: unless-stopped
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./adguard/conf:/opt/adguardhome/work
      - ./adguard/work:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/udp
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3001:3000/tcp
      - 853:853/tcp
      - 853:853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
      - 6060:6060/tcp
    restart: unless-stopped
  shinkro:
    image: ghcr.io/varoop/shinkro
    container_name: shinkro
    volumes:
      - ./shinkro/config:/config
    ports:
      - "7011:7011"
    restart: unless-stopped
    environment:
      - SHINKRO_USERNAME=shinkro
      - SHINKRO_PASSWORD=shinkro
      - PLEX_USERNAME=igorkulman
      - ANIME_LIBRARIES=Anime
      - PUID=1000
      - PGID=1000
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - ./bazarr/config:/config
      - /media/data:/media
    ports:
      - 6767:6767
    restart: unless-stopped
