---
version: "2.1"
services:  
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - UMASK=000
    volumes:
      - ./radarr/config:/config
      - /media/data:/media
    ports:
      - 7878:7878
    restart: unless-stopped
  flaresolverr:    
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Prague
    ports:
      - "8191:8191"
    restart: unless-stopped        
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - UMASK=000
    volumes:
      - ./sonarr/config:/config
      - /media/data:/media
    ports:
      - 8989:8989
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - UMASK=000
    volumes:
      - ./transmission/config:/config
      - /media/data/:/media
    ports:
      - 9091:9091
      - 49153:49153
      - 49153:49153/udp
    restart: unless-stopped
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Prague
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ./plex/:/config
      - /media/data:/media
      - /media/data/transcode:/transcode
    privileged: true
    devices:
      - /dev/dri:/dev/dri
  watchtower:
    image: containrrr/watchtower
    environment:            
      - WATCHTOWER_SCHEDULE=0 0 4 * * *            
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_NO_PULL=false
      - WATCHTOWER_MONITOR_ONLY=false
      - TZ=Europe/Prague
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./homepage/config:/app/config
      - ./homepage/icons:/app/public/icons
      - ./homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Prague
    volumes:
      - ./prowlarr:/config
    # networks:
    #   - noipv6
    restart: unless-stopped       
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./adguard/conf:/opt/adguardhome/work
      - ./adguard/work:/opt/adguardhome/conf
    ports:
      - 53:53/tcp 
      - 53:53/udp
      - 67:67/udp 
      - 68:68/udp
      - 80:80/tcp 
      - 443:443/tcp 
      - 443:443/udp 
      - 3001:3000/tcp
      - 853:853/tcp
      - 853:853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
      - 6060:6060/tcp
    restart: unless-stopped
